### ISSUE TITLE
Cannot read property 'toLowerCase' of null

### ISSUE THREAD

**Issue by iamjaytong** [tzkhan/pr-update-action#11]
```
##[error]TypeError: Cannot read property 'toLowerCase' of null
##[error]Cannot read property 'toLowerCase' of null
```

running into this issue for a PR that doesn't have a description/body (in this case, it's a pull request opened programmatically by a third party service). any chance the action can handle this case?

**Comment by tzkhan** [comment]
Thanks for raising this @iamjaytong.

I've published a new release with the bug fix so should work now. Make sure you point the action to `uses: tzkhan/pr-update-action@v1.1.1`

**Comment by iamjaytong** [comment]
works great, cheers!
