### ISSUE TITLE
Can I save %branch% somewhere and use it in a later step?

### ISSUE THREAD

**Issue by Abushawish** [tzkhan/pr-update-action#13]
I'm wondering if it's possible for me to save the result for %branch% somewhere like a variable and to use it later.

**Comment by tzkhan** [comment]
No, there are no outputs set within the action currently but it's a good shout. I'll be updating the action soon and will look to incorporate some output variables in those changes.

**Comment by tzkhan** [comment]
I've released `v2` that includes this and other features.
