### ISSUE TITLE
macro for target branch

### ISSUE THREAD

**Issue by vrothberg** [tzkhan/pr-update-action#14]
First off, thanks for the action! I find it very helpful and it matches exactly what I was looking for.

I have one use case where I want the prefix of the PR title to be the target branch name. The %branch% macro evaluates to the source branch of a PR but I am looking for a macro that evaluates to the target, so it's more obvious to maintainers if a PR is not against the main/master branch but against a stable branch, for instance.

I couldn't find a way to do it with the action. Is it already supported?

**Comment by joel-zilliqa** [comment]
I made a pr that resolves this issue.

https://github.com/tzkhan/pr-update-action/pull/15

**Comment by tzkhan** [comment]
I've released `v2` that includes this and other features.

**Comment by vrothberg** [comment]
Thanks to both of you!
